services:
  gpdp:
    build: .
    image: gpdp:latest
    container_name: gpdp
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./gpdp.properties:/app/gpdp.properties:ro
      - ./device.properties:/app/device.properties:ro
      # - ./logging.json:/app/logging.json:ro

  dispenser:
    image: ghcr.io/opekope2/aurora-dispenser:latest
    container_name: dispenser
    restart: unless-stopped
    # ports:
    #   - 3000:3000
    volumes:
      - ./accounts.txt:/app/resources/accounts.txt:ro
      # - ./logs:/logs
