services:
  gpdp:
    build: .
    image: gpdp:latest
    container_name: gpdp
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./gpdp.properties:/app/gpdp.properties:ro
      - ./device.properties:/app/device.properties:ro
      # - ./logging.json:/app/logging.json:ro
